language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

before_script:
  - composer self-update
  - composer install

script:
  - sh -c "vendor/bin/phpunit --coverage-clover clover.xml"

notifications:
  email: false